//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarKarusels = new HashSet<CarKarusel>();
            this.CarsReviews = new HashSet<CarsReview>();
            this.Rezervs = new HashSet<Rezerv>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public string SuretQutusu { get; set; }
        public string SernisinSayi { get; set; }
        public string Baqaj { get; set; }
        public int Klometraj { get; set; }
        public bool Status { get; set; }
        public string Sekil { get; set; }
        public System.DateTime Buraxilisili { get; set; }
        public System.DateTime ElaveEdilmeTarixi { get; set; }
        public int Qiymet1_3 { get; set; }
        public int Qiymet4_12 { get; set; }
        public int Qiymet12_30 { get; set; }
        public int Qiymet30GundenCox { get; set; }
        public int CarMarkalId { get; set; }
        public int CarClassId { get; set; }
        public int CarTypeId { get; set; }
    
        public virtual CarClass CarClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarKarusel> CarKarusels { get; set; }
        public virtual CarMarka CarMarka { get; set; }
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsReview> CarsReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezerv> Rezervs { get; set; }
    }
}
