//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudRezervChechBox
    {
        public int Id { get; set; }
        public int RezervId { get; set; }
        public int ChechBoxesId { get; set; }
    
        public virtual ChechBox ChechBox { get; set; }
        public virtual Rezerv Rezerv { get; set; }
    }
}
