//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerv()
        {
            this.CloudRezervChechBoxes = new HashSet<CloudRezervChechBox>();
        }
    
        public int Id { get; set; }
        public string Unvan { get; set; }
        public string Seker { get; set; }
        public string Olke { get; set; }
        public string Adres { get; set; }
        public string KartSifre { get; set; }
        public string ZipCode { get; set; }
        public bool Status { get; set; }
        public int CarId { get; set; }
        public int UserId { get; set; }
        public System.DateTime AlinmaTarix { get; set; }
        public System.DateTime QaytarilmaTarix { get; set; }
        public int UmmiMebleg { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CloudRezervChechBox> CloudRezervChechBoxes { get; set; }
        public virtual User User { get; set; }
    }
}
